name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "main" ] # main으로 향하는 PR에서만 작동

permissions:
  contents: read
  pull-requests: write # 댓글 권한 필수

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install google-generativeai PyGithub

      - name: Run AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
        shell: python
        run: |
          import os
          import google.generativeai as genai
          from github import Github

          # 환경 변수 로드
          repo_token = os.getenv('GITHUB_TOKEN')
          gemini_api_key = os.getenv('GEMINI_API_KEY')
          repo_name = os.getenv('REPO_NAME')
          pr_number = int(os.getenv('PR_NUMBER'))

          # Gemini 설정
          genai.configure(api_key=gemini_api_key)

          # 토스(Toss) 스타일 프롬프트
          SYSTEM_INSTRUCTION = """
          당신은 토스(Toss)의 'Frontend Chapter Lead'입니다.
          당신은 동료의 코드가 '변경하기 쉬운 코드'인지 4가지 핵심 기준(가독성, 예측 가능성, 응집도, 결합도)에 맞춰 리뷰합니다.

          [리뷰 핵심 철학]
          "좋은 코드는 변경하기 쉬운 코드다."

          [4가지 평가 기준]
          1. 가독성 (Readability): 맥락을 줄이고, 의도가 드러나는 네이밍을 사용했는가?
          2. 예측 가능성 (Predictability): 일관성 있는 구조와 타입을 유지했는가?
          3. 응집도 (Cohesion): 함께 수정되는 코드가 뭉쳐 있는가? (단, 트레이드오프 고려)
          4. 결합도 (Coupling): 모듈 간 의존성을 최소화했는가?

          [작성 가이드]
          - 개선이 필요한 부분이 있을 때만 지적하세요. (잘한 점 칭찬 생략)
          - 구체적인 '개선 코드 예시'를 마크다운 블록으로 작성하세요.
          - 한국어로 정중하게 작성하세요.
          """

          def get_pr_diff(repo, pr_num):
              pr = repo.get_pull(pr_num)
              diffs = []
              for file in pr.get_files():
                  # 프론트엔드 관련 파일만 필터링
                  if file.filename.endswith(('.js', '.jsx', '.ts', '.tsx', '.css', '.scss', '.html')):
                      patch = file.patch if file.patch else "No content"
                      # 토큰 절약을 위해 너무 긴 파일은 2000자까지만 자름
                      diffs.append(f"File: {file.filename}\\nDiff:\\n{patch[:2000]}\\n")
              return "\\n".join(diffs)

          def analyze_code(diff_content):
              model = genai.GenerativeModel(
                  model_name="gemini-1.5-flash",
                  system_instruction=SYSTEM_INSTRUCTION
              )
              prompt = f"""
              아래 변경된 코드를 리뷰해주세요.
              
              [Changes]
              {diff_content}
              """
              response = model.generate_content(prompt)
              return response.text

          try:
              g = Github(repo_token)
              repo = g.get_repo(repo_name)
              
              print(f"Checking PR #{pr_number} in {repo_name}...")
              diff_content = get_pr_diff(repo, pr_number)
              
              if not diff_content:
                  print("No changes detected in frontend files.")
              else:
                  print("Sending to Gemini...")
                  review_result = analyze_code(diff_content)
                  
                  print("Posting comment...")
                  repo.get_pull(pr_number).create_issue_comment(review_result)
                  print("Success!")
          except Exception as e:
              print(f"Error occurred: {e}")
              exit(1)